language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
notifications:
  email: false
script:
  - npm run syntax
  - npm test
after_script:
  - npm run coveralls
env:
  global:
    - secure: "RLqV9cKYw2yhFcXLvWEcSxrNw5K3ezQ3YeOcp/wJYSIOSlLffpdkDOIsn1FCUN1FwKSoLrQtOPOvXJ4LmluIPOXmWGyFlxXpCaPcaJfoDTesmPiCkl7/utg5RO7V+VKmGn/vl7p1kzVW8RE7oE4pINQeO7qJvy8Iguipf1eGxPA="
    - secure: "HpXL2/1qTzcNLajD4Aulae5/uVSNUj2mQ9/iYaw4vHCOhHTcZRtVfdcEMqrVM/cUBZWvUhlqKD+r3MxxnnwdQx/8f+E6qSOFmROQcltafVSn9gva1G2V0hoGVMf7gZNNDnpEa0MArsqA1b38ll/znwJyDyd6QGqiq10aOE3x81g="
    - secure: "Klid63pNBO8Rub03b6TgjxA1ITBCOZyyKPsvy+MM3UP3O54UfAvsemeHr//3cVOKi/4uh7I8Bsj5iaSPkURhV9q0NKhCPZu18EIbS5zvQHZ1V3qCAynOkiiRVRld4Q7DaIQForotMUVP3sgMChMBFIh86HTFJ6tjH47aO7W32fg="
    - secure: "Z2bZURwxAuO0EO/SuK9ZbY5/31OiLr91USf8IYqkuG5Ryp+fhmIJ9tpIAEnnLhOyQSq2Z4qjN84zjn+nzxF70I6ESEiGanM7BvFsOkVNdFMsCfHJfPy/EdKI8Z7LFmB1/XjW6HrK793lTpzYfuqtfceggTmc1tc/SRAFbDP4ME4="
